### ISSUE TITLE
White list problem

### ISSUE THREAD

**Issue by oRauu** [goryn-clade/pathfinder#105]
Well, i can't login to suite for every person i have bcoz of "Reason: failed to match alliance/corporation white list. Any idea how to fix that?

**Comment by samoneilll** [comment]
Hi there, sorry it's taken so long to respond. If you didn't already solve the issue, this is due to the whitelist that is created in the pathfinder.ini config file which can be found [here](https://github.com/goryn-clade/pathfinder/blob/master/app/pathfinder.ini#L80-L88).

If any of these options have a value set, then only the character/corp/alliance id listed will be allowed to log in
