### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by SpartaWarsec** [goryn-clade/pathfinder#107]
![Error 500](https://user-images.githubusercontent.com/52891531/154918384-64cb1666-238c-43b1-918b-c215ad95bd4f.jpeg)

after a server restart it worked again

I got this message from several people
V2.2.0

**Comment by MoNo7** [comment]
check your permissions for the folder
make sure your web server has access to these folders and files.  
cd /var/www

chown www-data:www-data pathfinder/*
chmod -R 755 /var/www/pathfinder

check your nginx logs
tail --lines=12 /var/www/pathfinder/public/logs/nginx_error.log

**Comment by samoneilll** [comment]
Hi there, sorry it's taken me a while to response. 

This error is caused when the JWT looks like it was issued in the future due to clock desync. In order to handle this server-clock desync that can happen we have set a leeway of 10 seconds. If you're finding that this is not sufficient, first check the system time on your server and make sure it's correct, and if doesn't solve it, consider adding some extra time to the leeway here: https://github.com/goryn-clade/pathfinder/blob/master/app/Controller/Ccp/Sso.php#L458-L460
