### ISSUE TITLE
[Bug] - Ghost Sites show as Data Sites

### ISSUE THREAD

**Issue by barndawgie** [goryn-clade/pathfinder#135]
If you scan down a Ghost Site (e.g. Improved Angel Covert Research Faciliity) and paste it into Pathfinder, it shows as a Data Site rather than a Ghost Site. Either the type "Ghost Site" should be removed or it should be correctly selected for sites for sites of this type.

**Comment by TyrHeimdalEVE** [comment]
Ref UniWiki: [Ghost Sites](https://wiki.eveuniversity.org/Ghost_Sites)

Must be added to [js/app/conf/signature_type.js](https://github.com/goryn-clade/pathfinder/blob/master/js/app/conf/signature_type.js).

> `<size>` `<faction>` Covert Research Facility

**Sizes**
- `Lesser` (high-sec)
- `Standard` (low-sec)
- `Improved` (null-sec)
- `Superior` (wormholes)

**Factions**
- `Serpentis`
- `Sansha's Nation`
- `Guristas`
- `Blood Raiders`

**Comment by samoneilll** [comment]
@barndawgie I've added definitions for ghost sites so that you can manually enter them. 

When you paste them in from probe scanner it won't pick these up automatically, since they are technically data sites. I don't think we want to deviate from what it says in game, but I will make sure in the next release that the ghost sites are available as data or ghost sites, so when you paste them it picks them up correctly, but you can also manually change the type to "ghost" if you want to differentiate.

I might keep this issue open for now as a reminder.

**Comment by TyrHeimdalEVE** [comment]
Closing as this was added in https://github.com/goryn-clade/pathfinder/commit/95bf96e1e21058e1e3fb26a4d0955cbc5b3324ed
