### ISSUE TITLE
Error 502 after Update

### ISSUE THREAD

**Issue by ppfeufer** [goryn-clade/pathfinder#47]
Just updated to the latest version and get an Error 502 after trying to login

![image](https://user-images.githubusercontent.com/2989985/138641597-d99a97b8-a324-4f4e-9d47-aa01a432202b.png)

**Comment by ppfeufer** [comment]
Found it.

`CCP_SSO_JWK_CLAIM` was missing in my `environment.ini`. Would be nice to mention that somewhere ...

But now I get a new error ...

![image](https://user-images.githubusercontent.com/2989985/138643439-b5508931-ec5d-4e91-b9e7-6bfeb5c5edc8.png)

**Comment by samoneilll** [comment]
Hey, I'm sorry, I missed updating the environment.ini in the docker-compose project, I've fixed it now.

The second error you're getting there is because the Db schema for storing access tokens changed. Go to your /setup page and run the "fix columns/keys" task on the "PF" database, and then try to log in again.

Edit: There's also a step by step upgrade guide here: 

https://github.com/goryn-clade/pathfinder-containers/wiki/v2.1.1----v2.1.4-Upgrade-Guide

**Comment by ppfeufer** [comment]
"fix columns/keys" is resulting in a foreign key constraint error ...

I nuked the DBs and rebuild them, working now ...

**Comment by samoneilll** [comment]
Okay, glad to hear it's working. Let me know if you run into any other issues.

**Comment by TyrHeimdalEVE** [comment]
The option (in /setup) to "Fix columns/keys" should fix both column types and foreign key constraints. You may have to run it multiple times.

In this specific case, character.esiAccessToken changed from varchar(256) to TEXT due to a change in length for tokens received from CCP's SSO API.

**Comment by samoneilll** [comment]
@ppfeufer I wonder if the foreign-key error you encoutered could be related to the issue you were having in https://github.com/goryn-clade/pathfinder/issues/39. It would be interesting to know if you're still having that issue pasting structures after rebuilding the db.

**Comment by ppfeufer** [comment]
Good point, no that is solved as well with nuking and rebuilding the DB ...

**Comment by samoneilll** [comment]
Cool, I'm going to close both issues then. There's definitely still other issues with pasting structures, but we have an open issue for it already
