### ISSUE TITLE
[BUG] System Neighbours build task does not run

### ISSUE THREAD

**Issue by TilleyTech** [goryn-clade/pathfinder#54]
After switching from main repo to this fork the routes section doesnt seem to work. Wont search or save any routes

**Comment by fleischsalatinspace** [comment]
From Slack: `Derek S: Nevermind.. just reimported eve_universe from safe copy and flushed cache, rebuild index worked, and routes are back. Carry on o/`

**Comment by TyrHeimdalEVE** [comment]
The neighbor index (in /setup) is only used as a fall-back in case ESI isn't available, but this should be looked at.

I have a sneaky suspicion this is related primarily due to changes made to implement Pochven and maybe other new systems.

**Comment by dascyklone** [comment]
This may not be the best place for this but I didn't feel like trying to update the Wiki... these are the steps I took for a bare metal upgrade from v2.0.2-tupsi to v.2.1.4 on Digital Ocean/Ubuntu 20.04.2 LTS running nginx/mysql/redis configuration.

Downloaded latest master from Github.
Unzipped into temp directory (listed here as "/tmp/pfsrc/").
Current Prod dir is listed here as "/pf/"

Created backup of existing database.
mysqldump -u <db_user> -p eve_universe --single-transaction --quick --lock-tables=false > ~/eve_universe-backup-$(date +%F).sql

Created backup of existing installation.
sudo cp -R /pf /tmp/pf-safe

Identified differences between current production and new master:
diff -qr /tmp/pfsrc /pf

Created symlink to update the public folder paths due to the version change. 
You can rename these, or use symlink as done below. Note you may have v2.0.0 here or something else; my original version was a fork (v2.0.2-tupsi) off Exodus, so I used that folder here. 

for DIR in css img js; do ln -ds /pf/public/${DIR}/v2.1.4 /pf/public/${DIR}/v2.0.2-tupsi; done

For each found file (except the .ini files), I copied from the new location to the production location. Each file I found different is listed below, this may vary depending on your original installation. 

cp /tmp/pfsrc/app/Controller/Admin.php /pf/app/Controller/Admin.php
cp /tmp/pfsrc/app/Controller/Api/GitHub.php /pf/app/Controller/Api/GitHub.php
cp /tmp/pfsrc/app/Controller/Api/Rest/Route.php /pf/app/Controller/Api/Rest/Route.php
cp /tmp/pfsrc/app/Controller/Api/Setup.php /pf/app/Controller/Api/Setup.php
cp /tmp/pfsrc/app/Controller/Ccp/Sso.php /pf/app/Controller/Ccp/Sso.php
cp /tmp/pfsrc/app/Controller/Controller.php /pf/app/Controller/Controller.php
cp /tmp/pfsrc/app/Db/Sql/Mysql/Column.php /pf/app/Db/Sql/Mysql/Column.php
cp /tmp/pfsrc/app/Db/Sql/Mysql/Constraint.php /pf/app/Db/Sql/Mysql/Constraint.php
cp /tmp/pfsrc/app/Db/Sql/Mysql/TableModifier.php /pf/app/Db/Sql/Mysql/TableModifier.php
cp /tmp/pfsrc/app/Model/Pathfinder/CharacterModel.php /pf/app/Model/Pathfinder/CharacterModel.php
cp /tmp/pfsrc/app/Model/Pathfinder/MapModel.php /pf/app/Model/Pathfinder/MapModel.php
cp /tmp/pfsrc/app/Model/Pathfinder/SystemModel.php /pf/app/Model/Pathfinder/SystemModel.php
cp /tmp/pfsrc/app/Model/Universe/AbstractUniverseModel.php /pf/app/Model/Universe/AbstractUniverseModel.php
cp /tmp/pfsrc/composer.json /pf/composer.json
cp /tmp/pfsrc/gulpfile.js /pf/gulpfile.js
cp /tmp/pfsrc/js/app/conf/signature_type.js /pf/js/app/conf/signature_type.js
cp /tmp/pfsrc/js/app/init.js /pf/js/app/init.js
cp /tmp/pfsrc/js/app/ui/module/system_intel.js /pf/js/app/ui/module/system_intel.js
cp /tmp/pfsrc/js/app/ui/module/system_killboard.js /pf/js/app/ui/module/system_killboard.js
cp /tmp/pfsrc/js/app/ui/module/system_route.js /pf/js/app/ui/module/system_route.js
cp /tmp/pfsrc/js/app/ui/module/system_signature.js /pf/js/app/ui/module/system_signature.js
cp /tmp/pfsrc/js/app/util.js /pf/js/app/util.js
cp /tmp/pfsrc/package.json /pf/package.json
cp /tmp/pfsrc/public/templates/dialog/map.html /pf/public/templates/dialog/map.html
cp /tmp/pfsrc/public/templates/dialog/route_settings.html /pf/public/templates/dialog/route_settings.html
cp /tmp/pfsrc/public/templates/ui/notice.html /pf/public/templates/ui/notice.html
cp /tmp/pfsrc/sass/layout/_main.scss /pf/sass/layout/_main.scss
cp /tmp/pfsrc/public/css/v2.1.4/pathfinder.css /pf/public/css/v2.1.4/pathfinder.css
cp /tmp/pfsrc/public/css/v2.1.4/pathfinder.css.br /pf/public/css/v2.1.4/pathfinder.css.br
cp /tmp/pfsrc/public/css/v2.1.4/pathfinder.css.map /pf/public/css/v2.1.4/pathfinder.css.map
cp /tmp/pfsrc/public/img/v2.1.4/gallery/development_1.webp /pf/public/img/v2.1.4/gallery/development_1.webp
cp /tmp/pfsrc/public/img/v2.1.4/gallery/intel_1.webp /pf/public/img/v2.1.4/gallery/intel_1.webp
cp /tmp/pfsrc/public/img/v2.1.4/gallery/route_1.webp /pf/public/img/v2.1.4/gallery/route_1.webp
cp /tmp/pfsrc/public/img/v2.1.4/gallery/system_2.webp /pf/public/img/v2.1.4/gallery/system_2.webp
cp /tmp/pfsrc/public/img/v2.1.4/gallery/thumbs/intel_1.webp /pf/public/img/v2.1.4/gallery/thumbs/intel_1.webp
cp /tmp/pfsrc/public/img/v2.1.4/gallery/thumbs/route_1.webp /pf/public/img/v2.1.4/gallery/thumbs/route_1.webp
cp /tmp/pfsrc/public/img/v2.1.4/header/pf-header-1200.jpg /pf/public/img/v2.1.4/header/pf-header-1200.jpg
cp /tmp/pfsrc/public/img/v2.1.4/header/pf-header-1600.jpg /pf/public/img/v2.1.4/header/pf-header-1600.jpg
cp /tmp/pfsrc/public/img/v2.1.4/header/pf-header-3840.jpg /pf/public/img/v2.1.4/header/pf-header-3840.jpg
cp /tmp/pfsrc/public/img/v2.1.4/header/pf-header-480.jpg /pf/public/img/v2.1.4/header/pf-header-480.jpg
cp /tmp/pfsrc/public/img/v2.1.4/header/pf-header-780.jpg /pf/public/img/v2.1.4/header/pf-header-780.jpg
cp /tmp/pfsrc/public/js/v2.1.4/app/admin.js /pf/public/js/v2.1.4/app/admin.js
cp /tmp/pfsrc/public/js/v2.1.4/app/admin.js.br /pf/public/js/v2.1.4/app/admin.js.br
cp /tmp/pfsrc/public/js/v2.1.4/app/admin.js.map /pf/public/js/v2.1.4/app/admin.js.map
cp /tmp/pfsrc/public/js/v2.1.4/app/login.js /pf/public/js/v2.1.4/app/login.js
cp /tmp/pfsrc/public/js/v2.1.4/app/login.js.br /pf/public/js/v2.1.4/app/login.js.br
cp /tmp/pfsrc/public/js/v2.1.4/app/login.js.map /pf/public/js/v2.1.4/app/login.js.map
cp /tmp/pfsrc/public/js/v2.1.4/app/mappage.js /pf/public/js/v2.1.4/app/mappage.js
cp /tmp/pfsrc/public/js/v2.1.4/app/mappage.js.br /pf/public/js/v2.1.4/app/mappage.js.br
cp /tmp/pfsrc/public/js/v2.1.4/app/mappage.js.map /pf/public/js/v2.1.4/app/mappage.js.map
cp /tmp/pfsrc/public/js/v2.1.4/app/setup.js /pf/public/js/v2.1.4/app/setup.js
cp /tmp/pfsrc/public/js/v2.1.4/app/setup.js.br /pf/public/js/v2.1.4/app/setup.js.br
cp /tmp/pfsrc/public/js/v2.1.4/app/setup.js.map /pf/public/js/v2.1.4/app/setup.js.map
cp /tmp/pfsrc/public/js/v2.1.4/app/summernote.loader.js /pf/public/js/v2.1.4/app/summernote.loader.js
cp /tmp/pfsrc/public/js/v2.1.4/app/summernote.loader.js.br /pf/public/js/v2.1.4/app/summernote.loader.js.br
cp /tmp/pfsrc/public/js/v2.1.4/app/summernote.loader.js.map /pf/public/js/v2.1.4/app/summernote.loader.js.map

For the configuration files, I didn't copy these, but did compare and add any missing lines (e.g JWT). Use diff -y <file> <file> to get an easy side by side view.

config.ini
environment.ini
pathfinder.ini
routes.ini

Ran chmod -R app-user:app-group on the production directory to fix any permission issues. 

Switched to application user and ran composer update to grab any new changes there. 

Restarted php-fpm and nginx.

Re-enabled setup page (uncomment Setup line in app/routes.ini).

Went to Setup page and began clearing all sessions, ran "fix columns/keys" on both databases, cleared redis cache, and all temp files at the bottom of the page. The Systems data index rebuild worked, but the neighbour index rebuild returned an error was stuck at 0.

![PF_Setup_Error](https://user-images.githubusercontent.com/93290309/139145877-6cf04332-66ef-4e64-9285-a936229e7484.png)

I tried reimporting the export/sql Pochven/Trailblazer file, but since that had already been applied, it ran into constraint errors. It would have worked if I emptied the tables, but I wasn't ready for that yet. Noticed the system_neighbour table was empty - which was why the index couldn't be rebuilt. 

Tried to fiddle around with the setup page (private session, different browser, etc.) and hunt for errors in the logs, and I did find the SQL error that was being thrown (didn't capture sorry!), but couldn't resolve it. So I just imported the database that I had backed up originally.

mysql -u <db_user> -p eve_universe < eve_universe-backup-2021-10-26.sql

The system_neighbour table was now populated, and I was able to rebuild indexes here and things were all showing green on the setup page.

Once I cleared browser cache (this was required for the Zkillboard fix!), I was able to re-auth via SSO and confirmed everything (including routes/Zkill update) were working normally again.

Asked users to test and confirmed things were back up for them also, after re-authenticating. I did have a report where a user needed to delete his customized routes and re-add in order to get routes to work for him. After this, he was working normally.

Hope this helps someone!

Derek

**Comment by MorphedAU** [comment]
Is this a duplicate of https://github.com/goryn-clade/pathfinder/issues/45 ?
Fix has been posted in the linked issue if so.

**Comment by fleischsalatinspace** [comment]
Might be duplicate. I posted the issue to OP on slack.

**Comment by samoneilll** [comment]
Definitely could be a duplicate, but I haven't had any time to investigate yet. I'll start looking into it sometime early November.

**Comment by TilleyTech** [comment]
All fixed, I applied fix from https://github.com/goryn-clade/pathfinder/issues/45 and also dropped the eve_universe database, recreated fresh blank db, cleared cache and setup the tables from /setup screen then re-imported the eve_universe sql from fresh from the goryn Clade fork. I then went back to /setup and the build worked for both the systems index and the neighborhood index. At first it didn't look like it worked but after I cleared browser cache and deleted existing routes I could add new routes such as Jita, Amarr etc and it works perfectly. Thankyou everyone

**Comment by oSkrobuk** [comment]
> All fixed, I applied fix from #45 and also dropped the eve_universe database, recreated fresh blank db, cleared cache and setup the tables from /setup screen then re-imported the eve_universe sql from fresh from the goryn Clade fork. I then went back to /setup and the build worked for both the systems index and the neighborhood index. At first it didn't look like it worked but after I cleared browser cache and deleted existing routes I could add new routes such as Jita, Amarr etc and it works perfectly. Thankyou everyone

It helped me

**Comment by samoneilll** [comment]
After pulling the fix from #45 I was able to drop systemNeighbours using the "Clear" button from the setup page and then run the rebuild task successfully.
