### ISSUE TITLE
The redirect URL does not match

### ISSUE THREAD

**Issue by CokkocZateki** [goryn-clade/pathfinder#67]
Hi

Having a issue with my Pathfinder. My App is def correct. tried making a second one to double check and still get the same issue

`{"error":"invalid_request","error_description":"The redirect URL does not match any of the configured values for this client."}`

**Comment by samoneilll** [comment]
Hi, 

This is caused when the `redirect_uri` query provided to login.eveonline.com does not match with the callback url that you set in the app in the eve developer portal. Usually it's an http vs https issue. 

When you're on the page with the error you can look in the address bar to find the `&redirect_uri=http....`, check that it matches with what you entered in the eve developer portal. If the escaped characters make it hard to check, you can also decode it easy with a site like https://www.urldecoder.org/.

I'm going to close this since it's not a PF issue, but if you need any more help with it feel free to join our slack server and we can provide more help there. https://join.slack.com/t/pathfinder-eve-online/shared_invite/zt-48z302c3-tkpZaYD0bgZwI7menDvPIA
